JustArchiNET/ASF-ui

src/style/_terminal.scss
This should also be tested under windows and linux. Right now I can only test on macOS.
=> Fix autocomplete for macOS, closes #18

LICENSE-2.0.txt
Since all other repositories have a license i thought why not add one to this repository.
=> Add license

package-lock.json, package.json, webpack.config.js
Replace `uglify-es` with `terser` for boosted performance.
=> Use `terser` to boost optimization performance

src/components/BGR/Status.vue
=> Improve recognizability for used/unused keys pop up, Closes #74

src/components/NavigationBots.vue
=> Allow up to 999 bots to be shown

src/store/modules/layout.js
=> Use small navigation when screen size < 700px

src/components/BotCard.vue
=> Add profile link to bot avatar

src/i18n/locale/default.json, src/views/Commands.vue
=> Add i18n support for terminal

src/components/AppNavigation.vue, src/i18n/locale/default.json, src/router/index.js, src/router/routes.js, src/views/UIConfiguration.vue
=> Add UI configuration

src/components/AppHeader.vue, src/components/Flag.vue, src/components/NavigationCategoryTitle.vue, src/components/NavigationLink.vue, src/views/Commands.vue, src/views/Setup.vue, src/views/modals/Bot.vue, src/views/modals/BotBGR.vue, src/views/modals/BotConfiguration.vue, src/views/modals/BotCreate.vue
It has no effect or is not working. Either way its unnecessary.
=> Remove metaInfo for Modal

src/plugins/sentry.js, webpack.config.js
=> Fallback to `no-git` version when `git` unavailable

.gitmodules, appveyor.yml, crowdin.yml
=> Initial crowdin support

src/components/ConfigFields/InputTag.vue
=> Improve InputTag config field

src/components/BotCard.vue, src/i18n/locale/default.json, src/store/modules/bots.js, src/store/modules/settings.js, src/views/UIConfiguration.vue, src/views/modals/Bot.vue, src/views/modals/BotBGR.vue, src/views/modals/BotConfiguration.vue, src/views/modals/BotDelete.vue
@Aareksio Can this be improved?
=> Show nickname (if available) instead of bot name

src/views/modals/Bot2FA.vue
=> Add loading symbol to 2fa buttons

src/i18n/locale/default.json, src/views/modals/BotBGR.vue
https://youtu.be/Tojb-L-Ubkg 😢
=> Use pluralization for keys count in BGR

src/components/BotGames.vue, src/i18n/locale/default.json, src/store/modules/settings.js, src/views/UIConfiguration.vue, src/views/modals/Bot.vue
=> Add option to hide game banner and only show game name

src/views/modals/Bot2FA.vue
https://stackoverflow.com/questions/21612058/letter-spacing-wrong-text-center-alignment
=> Center 2FA token

src/views/Commands.vue
Closes #337 
@Aareksio Should this get an option in UI Configuration?
=> Make terminal sign clickable to send command

src/views/modals/Bot2FA.vue
=> Show error message if token is null

src/App.vue
=> Optimize for small resolution

src/utils/fetchWiki.js, src/utils/getLocaleForWiki.js, src/utils/loadParameterDescriptions.js
=> Fetch wiki in users language

package-lock.json, package.json, src/components/AppFooter.vue, src/components/FooterLink.vue, src/components/FooterStatistic.vue, src/i18n/locale/default.json, src/plugins/icons.js
=> Optimize footer for smaller screens

src/components/AppFooter.vue, src/components/FooterLink.vue, src/components/FooterStatistic.vue, src/i18n/locale/default.json
=> Add hyperlinks to statistics in footer

src/App.vue, src/components/AppFooter.vue, src/components/FooterStatistic.vue, src/i18n/locale/default.json, src/plugins/icons.js, src/store/modules/settings.js, src/utils/ui.js, src/views/UIConfiguration.vue
=> Add option to get notified when a new release is available

src/components/BotCard.vue
=> Parse bit flag properly, right to left

src/components/AsfChangelog.vue
=> Add spacer to seperate releases

src/components/NavigationBrand.vue
@Aareksio Is there a specific reason why currently brand menu is being kept open after click?
=> Don't stop propagation to close brand menu

src/i18n/locale/default.json
Use `<code>` tag for `UpdateChannel` property, and add a missing dot.
=> Reformat i18n string "notify-release-description"

src/i18n/locale/default.json, src/views/modals/BotConfiguration.vue
=> Add i18n support for config property placeholder "keep unchanged"

src/utils/loadParameterDescriptions.js
=> Fix wiki links in config property descriptions

src/style/_form.scss
=> Improve visibility for config property descriptions

src/App.vue, src/components/AppModal.vue
=> Change modal background color for visibility reasons

src/App.vue, src/style/_form.scss
=> Change default button color for visibility reasons

src/views/Commands.vue
As [requested](https://www.reddit.com/r/Steam/comments/at6erv/asf_feedback_evaluation_you_can_help_us_too/egz8q4v/) in the reddit feedback thread
=> Aliasing `commands` to double tab when input is empty

src/App.vue
=> Fix modal background color for light mode

src/components/AsfBots.vue
=> Adjust bot placeholder height to fit bot card height

package-lock.json, src/i18n/locale/default.json, src/models/Bot.js, src/plugins/icons.js, src/views/modals/BotBGR.vue
Not sure about the layout. I think I like number 1 best... @JustArchi @Aareksio what do you think?
1 - Text under buttons             |  2 - Text above buttons
:-------------------------:|:-------------------------:
=> Add info about BGR background queue count

src/views/modals/BotConfiguration.vue
Fixes #468
Should be done long time ago...
=> Remove rename feature from bots

src/views/Commands.vue
@Abrynos, as you can [see](https://github.com/JustArchiNET/ASF-ui/issues/517#issuecomment-491360624) I like to change my mind frequently so here are your shortcuts.
Closes #517
=> Add terminal shortcuts

src/components/AppFooter.vue, src/utils/ui.js
=> Link to newest release in footer

src/i18n/locale/default.json, src/plugins/icons.js, src/views/modals/Bot2FA.vue
Closes #585
<details>
<summary>Screenshot</summary>
</details>
=> Change design of 2FA buttons

src/i18n/locale/default.json, src/store/modules/settings.js, src/style/_terminal.scss, src/views/Commands.vue, src/views/UIConfiguration.vue
=> Add option to show timestamps in terminal

src/components/BGR/Input.vue
=> Set focus to textfield upon loading BGR view

src/style/_form.scss
=> Improve visible separation of config categories

src/views/Commands.vue
_Thank god that I test my commits under mac **and** windows.. would be a shame if I would forget something very obvious..._
=> Fix terminal shortcuts

src/plugins/http.js
=> Update command api endpoint

src/components/AsfReleases.vue, src/utils/compareVersion.js
Update the logic of changelog fetch according to changes in ASF api as per #629 
Didn't have a chance to test it, as the ASF changes are not yet released, if someone could plug this PR to their build and see whether it actually works... 🤔 
Closes #691
=> Update fetching of asf release changelog to reflect ASF api changes

src/plugins/notifications.js
=> Set the default notification position

src/i18n/locale/default.json, src/views/UIConfiguration.vue
=> Move 'config categories' to general

.github/README.md, .github/workflows/ci.yml
@Aareksio check if you miss anything, merge if not 🙂.
=> Implement github workflow for ASF-ui

.github/README.md, src/components/AsfReleases.vue
=> Fix release date

src/components/AppFooter.vue, webpack.config.js
=> Add fallback if not git repo

src/views/Commands.vue
=> Fix auto-completion for bot names

.github/FEATURES.md, .github/README.md
=> Add info about hidden features

src/components/AppHeader.vue, src/components/AppSideMenu.vue, src/components/NavigationBrand.vue, src/components/NavigationLanguageSwitch.vue, src/store/modules/layout.js
=> Close menus with a click outside their element

src/i18n/locale/default.json, src/views/Commands.vue
The 'clear' command will clear the terminal screen.
=> Add 'clear' command to terminal

src/i18n/locale/default.json, src/views/modals/Bot2FA.vue
=> Rename buttons in 2FA modal

src/components/AppFooter.vue
Closes #1141 
@Botan626, could you please verify if this works as you suggested?
=> Redirect to 'Releases' page when clicking on 'new release' notifiaction

.github/FEATURES.md
Replaces the word 'button' with 'key' in Features.md
=> Change button to key in Features.md

.github/FEATURES.md
This will update the description for the "Ctrl + L" shortcut on the Commands page.
Closes #1151
=> Update description for Commands-shortcut "Ctrl + L"

src/components/AppModal.vue, src/plugins/icons.js, src/router/routes.js, src/views/modals/Bot2FA.vue, src/views/modals/BotConfiguration.vue
This should come in handy when you want to switch between bots while in modal view.
=> Add navigation arrows to bot modals

src/components/AsfReleases.vue, src/components/NavigationBrand.vue
Closes #1238
@Botan626 Feel free to test it.
=> Redirect to 'Log' page when clicking on 'trying to update' notification

src/utils/fetchWiki.js
=> Use new /Api/WWW/GitHub/Wiki endpoints for wiki calls

.github/FEATURES.md
More info added in the Global section.
=> Update Features.md #3

src/components/AsfReleases.vue, src/components/NavigationBrand.vue, src/i18n/locale/default.json, src/router/routes.js, src/views/ASFConfig.vue, src/views/Setup.vue
Fixes #1399
@Botan626 Please see if this fixes the issue for you.
=> Redirect to setup page upon restarting or updating

src/components/utils/Flag.vue
Fixed `lol-US.png` reference when used with base path.
=> Fix using lol-US flag with base path

src/components/ASF/Releases.vue
Fixes #1427
@Botan626 Feel free to verify if this works as expected.
=> Do not fetch release info for ASF versions that are newer than latest released

src/components/App/Modal.vue
Do not do weird stuff on Escape press
Closes #1424
=> Handle modal keypresses only when modal is shown

src/i18n/lib/formatter.js
CLDR table does not recognize lol-US as a valid locale
Closes #1436
=> Fix pluralization for lol-US

src/components/ASF/Bots.vue, src/components/Bot/Card.vue
I guess this works
Closes #402
=> Change how bot card responds to screen size

src/App.vue, src/router/routes.js, src/store/modules/settings.js, src/views/Setup.vue
- handle navigation abort by home alias redirect
- handle endless loop caused by defaultView set to "home"
- handle repetitive navigation to Setup page while already on Setup page
Closes #1422
=> Fix unnecessary errors when redirecting on Setup page

scripts/reverse-proxy/index.js, scripts/reverse-proxy/package-lock.json, scripts/reverse-proxy/package.json, src/index.html, src/index.js, src/router/routes.js
TLDR: Respect public path
I considered the following possible options of running ASF-ui:
- under root directory, eg `http://localhost:1242`
- under sub-direcory, eg. `http://localhost:1242/ASF`
- under multi-level sub-directory, eg. `http://localhost:1242/path/to/ASF`
Previous public path method relied on `/page` in the URL to find the correct base path on first try, new method attempts to load the main script (`main.[hash].bundle.js`) from each level of the hierarchy.
Consider the complex URL: `http://localhost:1242/path/to/ASF/bots/test/config`
The public path is `/path/to/ASF`, it should open `/bots/:bot/config` page
The proposed solution will attempt to load the main script from the following paths:
- `/scripts/main.bundle.js` - default attempt - miss
- …
=> Implement more sophisticated public path testing

package-lock.json, package.json, src/index.html, webpack/config.js, webpack/config.prod.js
Browser should now check integrity of the requested scripts. This ensures we do not execute malicious JavaScript if served such.
Read comments here:
<https://github.com/JustArchiNET/ASF-ui/pull/1468#issuecomment-873572484>
=> Add SRI for main script

src/components/MassEditor/Steps.vue, src/views/MassEditor.vue
=> Add step wizard to Mass Editor

src/components/MassEditor/Steps.vue
=> Improve styling for steps in Mass Editor

src/index.html
This should fix a bug that Abrynos [mentioned on discord](https://discord.com/channels/267292556709068800/859553121856258058/877500869141229608).
=> Add `crossorigin` to manifest link

src/components/Bot/Card.vue, src/store/modules/asf.js, src/views/modals/Bot.vue
Closes #1542 
@JustArchi, please feel free to give this a quick test.
=> Support `--service` cmd line arg for headless detection

src/components/ASF/Bots.vue, src/store/modules/bots.js
Bots on Bots page will be sorted alphabetically like `status asf` command output.
=> Show bots in alphabetical order on Bots page

src/i18n/locale/default.json, src/router/index.js, src/router/routes.js, src/store/modules/asf.js, src/views/Welcome.vue
=> Do not ask for SteamOwnerID anymore

src/router/routes.js
This should fix #1556, sorry for the delayed PR.
=> Fix infinite loading loop

src/components/ASF/Bots.vue, src/i18n/locale/default.json, src/store/modules/settings.js, src/utils/configCategories.js, src/views/UIConfig.vue
Closes #1587
@dd410 Feel free to check if this is what you had in mind.
=> Add config option for changing bot order

src/i18n/locale/default.json, src/style/_terminal.scss
=> Preserve the extra spaces in UI terminal

src/components/Navigation/Link.vue
=> Fix nav link height for different zoom level

src/i18n/locale/default.json, src/views/Commands.vue
Relates to: https://github.com/JustArchiNET/ASF-ui/issues/1605
=> Add default log displaying help text

src/components/Config/Editor.vue
@JustArchi Could you check and verify that this bug is now fixed?
Fixes #1596
=> Preserve user-defined order of `ImmutableList`

package-lock.json, package.json, src/components/ASF/Releases.vue
Archi stopped using emojis in ASF release notes
=> Remove emojis from release notes
