src/style/_terminal.scss
e.g.: `statusall` outputs multiple line breaks characters (`\n`) that are ignored when displayed in the page.
=> Preserve line breaks from command output

.travis.yml, appveyor.yml, package.json
ASF-ui CIs (AppVeyor and Travis) do not get along with `--progress`, and I want them to use `build` and not `deploy` as `deploy` should be reserved for main ASF and situations where you intend to include super-minified no-debug build.
Therefore I think that normal production build does not need `--progress`, as any eventual speed of compilation and feedback is already available in `dev` build.
Alternatively, we might want to add yet another action such as `ci` but I find it unnecessarily excessive. I'm pretty sure that you can add `--progress` yourself if you need it, no need to specify it as default value.
cc @Aareksio
=> Add build:ci action

src/components/AsfLog.vue
Before            |  After
:-------------------------:|:-------------------------:
=> Readd "|" symbol for log text

src/i18n/locale/default.json
https://github.com/JustArchiNET/ASF-ui/blob/20723dbcec0a7faa6d7e9c899520fe791b1caa2d/src/views/modals/BotConfiguration.vue#L50
^ this entry is still using here
=> Add missing "farming" bot config category i18n entry

src/components/AsfBots.vue
gif was taken on mac, chrome v74.0.3
=> Add some space between bots and footer

src/components/AsfLog.vue
=> Fix 'Invalid Date' in log for safari on iOS

src/components/BotCard.vue, src/views/modals/Bot.vue
This should be useful if you have the option "Show nicknames" turned on but still want to have a way of knowing the bot name.
=> Show bot name on mouse over for bot nickname

src/components/NavigationBrand.vue
As per the ASF wiki:
>Setting UpdateChannel to 0 will entirely disable entire functionality related to updates, including update command.
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#updatechannel
If `UpdateChannel` is `0`:
If `UpdateChannel` is not `0`:
=> Hide the "Update" menu when UpdateChannel is 0

src/components/AsfReleases.vue
Clean up the code a little, make sure there are no duplicates on the list if we store version in different format than the API returns. 
Closes #722 
From Botan's screens I suspect either the `version` might not yet be fetched from ASF API, or it was stored differently than the result of changelog endpoints. Either way, this PR should prevent duplicates to be shown.
I think in Botan's case the issue was caused by having the releases page set as default page of ASF-ui, which caused the requests fetching releases to be fired prior to loading the current version from `/asf` endpoint. We could prevent this (and similar) issues from happening by using a check in router's `beforeRoute` hook, that'd delay loading a page until we connect with ASF.
=> Make sure we do not show the same release note twice

src/views/modals/Bot2FA.vue
The goal of this PR is to follow new API endpoint `/Api/Bot/{botNames}/TwoFactorAuthentication/Confirmations` and to make sure that nothing will break upon next stable ASF release.
Related: #1075
=> Move to new API endpoint for handling confirmations

package.json
`webpack-dev-server` standalone use along webpack-cli 4 have been discouraged as per webpack/webpack-dev-server#2424
=> Replace `webpack-dev-server` with `webpack serve` command

src/utils/ui.js
Fixes #1150 
I've set the limit to one request per hour. This means that ASF-ui will now check every hour (if the mounted event for the footer gets triggered aka. page reload) for an update. This could also be a potential new UI configuration. So user can set it to 1 hour, 1 day or turn it off.
=> Only send one request per hour to 'www/send'

package-lock.json, package.json, src/index.html, webpack/config.js
This change allows us to use `[hash]` in script path. Using `[hash]` in script path should bust the cache whenever ASF build changes. This _should_ fix UI being non-functional after update due to loading old main.bundle.js from browser cache.
The `.replace('//', '/')` is hacky, idk, probably can be done better :)
Closes #1330
=> Use HTML Webpack Plugin to inject script path into HTML

src/components/ConfigEditor.vue, src/components/ConfigFields/InputFlag.vue, src/components/ConfigFields/InputList.vue, src/components/ConfigFields/InputSet.vue, src/i18n/locale/default.json
Implements #1449 for `InputFlag`, `InputSet` and `InputList`.
I'd propose renaming the three above mentioned components to contain the n word "Enum", since they are exclusively used for that and the name implies a more generic usage (e.g. them also being used for config fields such as `GamesPlayedWhileIdle`, which is also `ImmutableHashSet<...>` under the hood), but I have no idea of how to do this.
=> Implement #1449 - speed up configuration workflow

src/style/_form.scss, src/views/Setup.vue, src/views/modals/BotInput.vue
This merge request adds a "show password" button to the setup page. This is a recommendation for safe passwords per NIST:
> In order to assist the claimant in successfully entering a memorized secret, the verifier SHOULD offer an option to display the secret — rather than a series of dots or asterisks — until it is entered. This allows the claimant to verify their entry if they are in a location where their screen is unlikely to be observed.
Giving the user an option to check whether they made a typo increases their chance of choosing a longer, safer password in the first place.
Since we already had similar logic for the modal that opens when a bot instance requires input, it was a pretty straight-forward implementation. 😁
=> Add "show password" button to setup page

src/components/utils/FitText.vue
With DPI scaling the number of bots is displayed incorrectly in Google Chrome
Before:
After:
=> fix with DPI Scaling

src/components/Navigation/Statistic.vue
I notice the console keep print `vue warn` in develop mode. Because in `Statistic.vue`, the props named `value` expected a `String`, but got a `Number`. Now it can get `Number` or `String`.
=> fix: props type error

.github/ISSUE_TEMPLATE/Question.yml
ASF core doesn't want support questions to be issues. They should be discussions instead. Reflect this in the link of the issue template for questions in this repository.
Thank you for considering the inclusion of this merge request.
=> Link to ASF discussions instead of issues for questions

src/utils/swagger/parse.js
By some mistake ASF-ui uses localhost:8080 as base url for one of requests. Not only it uses outright wrong port, but also will not work when accessing ASF-ui not from localhost. I changed it to be relative path instead. As a consequence of this bug steam wallet funds were not shown in ASF-ui (https://steamcommunity.com/groups/archiasf/discussions/1/3459347019172139874/ for reference)
Without this fix:
With this fix:
I checked and it works for me.
=> Fix endpoint path to be relative

src/utils/swagger/parse.js
Use base path when fetching swagger data, fixes not showing bot’s balance with base path.
None
Closes https://github.com/JustArchiNET/ASF-ui/issues/1663
=> Fix fetching swagger data when using base path

src/views/ASFConfig.vue, src/views/modals/BotConfig.vue
Fixes this issue - https://github.com/JustArchiNET/ASF-ui/issues/1651
<details>
<summary>Changing <code>passwordFormat</code> to <code>AES</code></summary>
</details>
<details>
<summary>New value for <code>passwordFormat</code></summary>
</details>
The issue is that if user didn't come from `PasswordEncrypt.vue`, then values in `this.$route.params` are `undefined` and thus they overwrite existing `passwordFormat` value
=> Fix ASF-ui wrong password format

src/router/routes.js
Fixes this issue https://github.com/JustArchiNET/ASF-ui/issues/1496
<details>
<summary>Network activity< (<code>/</code> path)</summary>
</details>
Instead of redirecting to the `home` page and causing a loop, it redirects the user to the `bots` page
=> Fix an infinite redirect loop when settings:default-view is set to home
